### ISSUE TITLE
Which version of the Scratch 1.4 source code was used to make KitKat?

### ISSUE THREAD

**Issue by techboyg5** [retro-person/KitKat#1]
I want to make a pull request adding a `LICENSE` file.

But I can't do that right now because there are [two versions of Scratch 1.4, under different licenses](https://en.scratch-wiki.info/wiki/Scratch_1.4_Source_Code). Can you please tell me what version you used when making KitKat?

Here are the differences I notice between the two versions:
* SSCL version: No Scratch logo, no Scratch cat, no project sharing code
* GPL version: Looks and functions exactly like the [binary version](https://scratch.mit.edu/scratch_1.4) of Scratch 1.4

**Comment by retro-person** [comment]
> I want to make a pull request adding a `LICENSE` file.
> 
> But I can't do that right now because there are [two versions of Scratch 1.4, under different licenses](https://en.scratch-wiki.info/wiki/Scratch_1.4_Source_Code). Can you please tell me what version you used when making KitKat?
> 
> Here are the differences I notice between the two versions:
> 
> * SSCL version: No Scratch logo, no Scratch cat, no project sharing code
> * GPL version: Looks and functions exactly like the [binary version](https://scratch.mit.edu/scratch_1.4) of Scratch 1.4

I'm pretty sure I used [this](http://download.scratch.mit.edu/source-code/ScratchSource1.4.zip) SSCL-licensed version of Scratch 1.4. Also, I have a license-related question: There's this OS called [IRIX](https://en.wikipedia.org/wiki/IRIX) for which I would like to create an installation guide. I want to put a disk image of it in my [website repository](https://github.com/retro-person/retro-person.github.io) to link to in the guide. Since you know more about legal and licensing things, could you tell me if I would infringe on any copyrights here? However, user [shrek](https://forums.irixnet.org/user-462.html) on the IRIX forums has given a link, supposedly uploaded by themselves, at [I would've linked to their topic; I didn't find it, but a mention of their topic is [here](https://forums.irixnet.org/thread-1898.html)]; because of this, I do not know whether it is legal to upload such a file, especially to GitHub, with it being open-source-oriented. Also, I could find any topics on the IRIX forums nor any mentions of still-surviving copyright claims on IRIX's Wikipedia article. However, in IRIX's Wikipedia article it is said that Silicon Graphics, Inc., the producers of IRIX, went bankrupt in 2009. However, I do not know if a company still owns copyright claims after bankruptcy. Help would be greatly appreciated!

**Comment by techboyg5** [comment]
> > I want to make a pull request adding a `LICENSE` file.
> > But I can't do that right now because there are [two versions of Scratch 1.4, under different licenses](https://en.scratch-wiki.info/wiki/Scratch_1.4_Source_Code). Can you please tell me what version you used when making KitKat?
> > Here are the differences I notice between the two versions:
> > 
> > * SSCL version: No Scratch logo, no Scratch cat, no project sharing code
> > * GPL version: Looks and functions exactly like the [binary version](https://scratch.mit.edu/scratch_1.4) of Scratch 1.4
> 
> I'm pretty sure I used [this](http://download.scratch.mit.edu/source-code/ScratchSource1.4.zip) SSCL-licensed version of Scratch 1.4. Also, I have a license-related question: There's this OS called [IRIX](https://en.wikipedia.org/wiki/IRIX) for which I would like to create an installation guide. I want to put a disk image of it in my [website repository](https://github.com/retro-person/retro-person.github.io) to link to in the guide. Since you know more about legal and licensing things, could you tell me if I would infringe on any copyrights here? However, user [shrek](https://forums.irixnet.org/user-462.html) on the IRIX forums has given a link, supposedly uploaded by themselves, at [I would've linked to their topic; I didn't find it, but a mention of their topic is [here](https://forums.irixnet.org/thread-1898.html)]; because of this, I do not know whether it is legal to upload such a file, especially to GitHub, with it being open-source-oriented. Also, I could find any topics on the IRIX forums nor any mentions of still-surviving copyright claims on IRIX's Wikipedia article. However, in IRIX's Wikipedia article it is said that Silicon Graphics, Inc., the producers of IRIX, went bankrupt in 2009. However, I do not know if a company still owns copyright claims after bankruptcy. Help would be greatly appreciated!

The IRIX license is proprietary, so I'm pretty sure you cannot do that.

**Comment by retro-person** [comment]
> > > I want to make a pull request adding a `LICENSE` file.
> > > But I can't do that right now because there are [two versions of Scratch 1.4, under different licenses](https://en.scratch-wiki.info/wiki/Scratch_1.4_Source_Code). Can you please tell me what version you used when making KitKat?
> > > Here are the differences I notice between the two versions:
> > > 
> > > * SSCL version: No Scratch logo, no Scratch cat, no project sharing code
> > > * GPL version: Looks and functions exactly like the [binary version](https://scratch.mit.edu/scratch_1.4) of Scratch 1.4
> > 
> > 
> > I'm pretty sure I used [this](http://download.scratch.mit.edu/source-code/ScratchSource1.4.zip) SSCL-licensed version of Scratch 1.4. Also, I have a license-related question: There's this OS called [IRIX](https://en.wikipedia.org/wiki/IRIX) for which I would like to create an installation guide. I want to put a disk image of it in my [website repository](https://github.com/retro-person/retro-person.github.io) to link to in the guide. Since you know more about legal and licensing things, could you tell me if I would infringe on any copyrights here? However, user [shrek](https://forums.irixnet.org/user-462.html) on the IRIX forums has given a link, supposedly uploaded by themselves, at [I would've linked to their topic; I didn't find it, but a mention of their topic is [here](https://forums.irixnet.org/thread-1898.html)]; because of this, I do not know whether it is legal to upload such a file, especially to GitHub, with it being open-source-oriented. Also, I could find any topics on the IRIX forums nor any mentions of still-surviving copyright claims on IRIX's Wikipedia article. However, in IRIX's Wikipedia article it is said that Silicon Graphics, Inc., the producers of IRIX, went bankrupt in 2009. However, I do not know if a company still owns copyright claims after bankruptcy. Help would be greatly appreciated!
> 
> The IRIX license is proprietary, so I'm pretty sure you cannot do that.

Ah, okay. However, how do you think user shrek uploaded the file without legal trouble?

**Comment by techboyg5** [comment]
> > > > I want to make a pull request adding a `LICENSE` file.
> > > > But I can't do that right now because there are [two versions of Scratch 1.4, under different licenses](https://en.scratch-wiki.info/wiki/Scratch_1.4_Source_Code). Can you please tell me what version you used when making KitKat?
> > > > Here are the differences I notice between the two versions:
> > > > 
> > > > * SSCL version: No Scratch logo, no Scratch cat, no project sharing code
> > > > * GPL version: Looks and functions exactly like the [binary version](https://scratch.mit.edu/scratch_1.4) of Scratch 1.4
> > > 
> > > 
> > > I'm pretty sure I used [this](http://download.scratch.mit.edu/source-code/ScratchSource1.4.zip) SSCL-licensed version of Scratch 1.4. Also, I have a license-related question: There's this OS called [IRIX](https://en.wikipedia.org/wiki/IRIX) for which I would like to create an installation guide. I want to put a disk image of it in my [website repository](https://github.com/retro-person/retro-person.github.io) to link to in the guide. Since you know more about legal and licensing things, could you tell me if I would infringe on any copyrights here? However, user [shrek](https://forums.irixnet.org/user-462.html) on the IRIX forums has given a link, supposedly uploaded by themselves, at [I would've linked to their topic; I didn't find it, but a mention of their topic is [here](https://forums.irixnet.org/thread-1898.html)]; because of this, I do not know whether it is legal to upload such a file, especially to GitHub, with it being open-source-oriented. Also, I could find any topics on the IRIX forums nor any mentions of still-surviving copyright claims on IRIX's Wikipedia article. However, in IRIX's Wikipedia article it is said that Silicon Graphics, Inc., the producers of IRIX, went bankrupt in 2009. However, I do not know if a company still owns copyright claims after bankruptcy. Help would be greatly appreciated!
> > 
> > 
> > The IRIX license is proprietary, so I'm pretty sure you cannot do that.
> 
> Ah, okay. However, how do you think user shrek uploaded the file without legal trouble?

That user is either doing it illegally, or has permission to do that by the developers of IRIX.

The new PR for the license is #2.

**Comment by retro-person** [comment]
> > > > > I want to make a pull request adding a `LICENSE` file.
> > > > > But I can't do that right now because there are [two versions of Scratch 1.4, under different licenses](https://en.scratch-wiki.info/wiki/Scratch_1.4_Source_Code). Can you please tell me what version you used when making KitKat?
> > > > > Here are the differences I notice between the two versions:
> > > > > 
> > > > > * SSCL version: No Scratch logo, no Scratch cat, no project sharing code
> > > > > * GPL version: Looks and functions exactly like the [binary version](https://scratch.mit.edu/scratch_1.4) of Scratch 1.4
> > > > 
> > > > 
> > > > I'm pretty sure I used [this](http://download.scratch.mit.edu/source-code/ScratchSource1.4.zip) SSCL-licensed version of Scratch 1.4. Also, I have a license-related question: There's this OS called [IRIX](https://en.wikipedia.org/wiki/IRIX) for which I would like to create an installation guide. I want to put a disk image of it in my [website repository](https://github.com/retro-person/retro-person.github.io) to link to in the guide. Since you know more about legal and licensing things, could you tell me if I would infringe on any copyrights here? However, user [shrek](https://forums.irixnet.org/user-462.html) on the IRIX forums has given a link, supposedly uploaded by themselves, at [I would've linked to their topic; I didn't find it, but a mention of their topic is [here](https://forums.irixnet.org/thread-1898.html)]; because of this, I do not know whether it is legal to upload such a file, especially to GitHub, with it being open-source-oriented. Also, I could find any topics on the IRIX forums nor any mentions of still-surviving copyright claims on IRIX's Wikipedia article. However, in IRIX's Wikipedia article it is said that Silicon Graphics, Inc., the producers of IRIX, went bankrupt in 2009. However, I do not know if a company still owns copyright claims after bankruptcy. Help would be greatly appreciated!
> > > 
> > > 
> > > The IRIX license is proprietary, so I'm pretty sure you cannot do that.
> > 
> > 
> > Ah, okay. However, how do you think user shrek uploaded the file without legal trouble?
> 
> That user is either doing it illegally, or has permission to do that by the copyright holders of IRIX.
> 
> I created a new license pull request #2.

Thank you! Merged.

**Comment by retro-person** [comment]
Also, does use of the word "KItKat" for the name of my modification infringe on the chocolate company KitKat's copyrights? Also, is the "unaffiliatory" statement that I added into the README.md help in any way? And is there a similar one I could add to my website repository if I wanted to add the IRIX image?
